from .physics import (TEST_FUNCTION,
                      FALLING_BODY_SPEED_FUNCTION,
                      WIRE_HEIGHT_FUNCTION)


FUNCTIONS = [
    FALLING_BODY_SPEED_FUNCTION,
    WIRE_HEIGHT_FUNCTION
]
